# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/cryptoeng/SLWL11

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/cryptoeng/SLWL11

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/cryptoeng/SLWL11/CMakeFiles /home/ubuntu/cryptoeng/SLWL11//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/cryptoeng/SLWL11/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mdr

# Build rule for target.
mdr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mdr
.PHONY : mdr

# fast build rule for target.
mdr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/build
.PHONY : mdr/fast

#=============================================================================
# Target rules for targets named elgamal-mod

# Build rule for target.
elgamal-mod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 elgamal-mod
.PHONY : elgamal-mod

# fast build rule for target.
elgamal-mod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elgamal-mod.dir/build.make CMakeFiles/elgamal-mod.dir/build
.PHONY : elgamal-mod/fast

#=============================================================================
# Target rules for targets named anon-proxy

# Build rule for target.
anon-proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 anon-proxy
.PHONY : anon-proxy

# fast build rule for target.
anon-proxy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anon-proxy.dir/build.make CMakeFiles/anon-proxy.dir/build
.PHONY : anon-proxy/fast

#=============================================================================
# Target rules for targets named main-elgamal-mod

# Build rule for target.
main-elgamal-mod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-elgamal-mod
.PHONY : main-elgamal-mod

# fast build rule for target.
main-elgamal-mod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-elgamal-mod.dir/build.make CMakeFiles/main-elgamal-mod.dir/build
.PHONY : main-elgamal-mod/fast

#=============================================================================
# Target rules for targets named test-elgamal-mod

# Build rule for target.
test-elgamal-mod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-elgamal-mod
.PHONY : test-elgamal-mod

# fast build rule for target.
test-elgamal-mod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-elgamal-mod.dir/build.make CMakeFiles/test-elgamal-mod.dir/build
.PHONY : test-elgamal-mod/fast

#=============================================================================
# Target rules for targets named main-anon-proxy

# Build rule for target.
main-anon-proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-anon-proxy
.PHONY : main-anon-proxy

# fast build rule for target.
main-anon-proxy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-anon-proxy.dir/build.make CMakeFiles/main-anon-proxy.dir/build
.PHONY : main-anon-proxy/fast

#=============================================================================
# Target rules for targets named test-anon-proxy

# Build rule for target.
test-anon-proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-anon-proxy
.PHONY : test-anon-proxy

# fast build rule for target.
test-anon-proxy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-anon-proxy.dir/build.make CMakeFiles/test-anon-proxy.dir/build
.PHONY : test-anon-proxy/fast

examples/main-anon-proxy.o: examples/main-anon-proxy.c.o
.PHONY : examples/main-anon-proxy.o

# target to build an object file
examples/main-anon-proxy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-anon-proxy.dir/build.make CMakeFiles/main-anon-proxy.dir/examples/main-anon-proxy.c.o
.PHONY : examples/main-anon-proxy.c.o

examples/main-anon-proxy.i: examples/main-anon-proxy.c.i
.PHONY : examples/main-anon-proxy.i

# target to preprocess a source file
examples/main-anon-proxy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-anon-proxy.dir/build.make CMakeFiles/main-anon-proxy.dir/examples/main-anon-proxy.c.i
.PHONY : examples/main-anon-proxy.c.i

examples/main-anon-proxy.s: examples/main-anon-proxy.c.s
.PHONY : examples/main-anon-proxy.s

# target to generate assembly for a file
examples/main-anon-proxy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-anon-proxy.dir/build.make CMakeFiles/main-anon-proxy.dir/examples/main-anon-proxy.c.s
.PHONY : examples/main-anon-proxy.c.s

examples/main-elgamal-mod.o: examples/main-elgamal-mod.c.o
.PHONY : examples/main-elgamal-mod.o

# target to build an object file
examples/main-elgamal-mod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-elgamal-mod.dir/build.make CMakeFiles/main-elgamal-mod.dir/examples/main-elgamal-mod.c.o
.PHONY : examples/main-elgamal-mod.c.o

examples/main-elgamal-mod.i: examples/main-elgamal-mod.c.i
.PHONY : examples/main-elgamal-mod.i

# target to preprocess a source file
examples/main-elgamal-mod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-elgamal-mod.dir/build.make CMakeFiles/main-elgamal-mod.dir/examples/main-elgamal-mod.c.i
.PHONY : examples/main-elgamal-mod.c.i

examples/main-elgamal-mod.s: examples/main-elgamal-mod.c.s
.PHONY : examples/main-elgamal-mod.s

# target to generate assembly for a file
examples/main-elgamal-mod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-elgamal-mod.dir/build.make CMakeFiles/main-elgamal-mod.dir/examples/main-elgamal-mod.c.s
.PHONY : examples/main-elgamal-mod.c.s

libs-mdr/lib-mesg.o: libs-mdr/lib-mesg.c.o
.PHONY : libs-mdr/lib-mesg.o

# target to build an object file
libs-mdr/lib-mesg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-mesg.c.o
.PHONY : libs-mdr/lib-mesg.c.o

libs-mdr/lib-mesg.i: libs-mdr/lib-mesg.c.i
.PHONY : libs-mdr/lib-mesg.i

# target to preprocess a source file
libs-mdr/lib-mesg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-mesg.c.i
.PHONY : libs-mdr/lib-mesg.c.i

libs-mdr/lib-mesg.s: libs-mdr/lib-mesg.c.s
.PHONY : libs-mdr/lib-mesg.s

# target to generate assembly for a file
libs-mdr/lib-mesg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-mesg.c.s
.PHONY : libs-mdr/lib-mesg.c.s

libs-mdr/lib-misc.o: libs-mdr/lib-misc.c.o
.PHONY : libs-mdr/lib-misc.o

# target to build an object file
libs-mdr/lib-misc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-misc.c.o
.PHONY : libs-mdr/lib-misc.c.o

libs-mdr/lib-misc.i: libs-mdr/lib-misc.c.i
.PHONY : libs-mdr/lib-misc.i

# target to preprocess a source file
libs-mdr/lib-misc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-misc.c.i
.PHONY : libs-mdr/lib-misc.c.i

libs-mdr/lib-misc.s: libs-mdr/lib-misc.c.s
.PHONY : libs-mdr/lib-misc.s

# target to generate assembly for a file
libs-mdr/lib-misc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-misc.c.s
.PHONY : libs-mdr/lib-misc.c.s

libs-mdr/lib-powm.o: libs-mdr/lib-powm.c.o
.PHONY : libs-mdr/lib-powm.o

# target to build an object file
libs-mdr/lib-powm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-powm.c.o
.PHONY : libs-mdr/lib-powm.c.o

libs-mdr/lib-powm.i: libs-mdr/lib-powm.c.i
.PHONY : libs-mdr/lib-powm.i

# target to preprocess a source file
libs-mdr/lib-powm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-powm.c.i
.PHONY : libs-mdr/lib-powm.c.i

libs-mdr/lib-powm.s: libs-mdr/lib-powm.c.s
.PHONY : libs-mdr/lib-powm.s

# target to generate assembly for a file
libs-mdr/lib-powm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-powm.c.s
.PHONY : libs-mdr/lib-powm.c.s

libs-mdr/lib-timing.o: libs-mdr/lib-timing.c.o
.PHONY : libs-mdr/lib-timing.o

# target to build an object file
libs-mdr/lib-timing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-timing.c.o
.PHONY : libs-mdr/lib-timing.c.o

libs-mdr/lib-timing.i: libs-mdr/lib-timing.c.i
.PHONY : libs-mdr/lib-timing.i

# target to preprocess a source file
libs-mdr/lib-timing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-timing.c.i
.PHONY : libs-mdr/lib-timing.c.i

libs-mdr/lib-timing.s: libs-mdr/lib-timing.c.s
.PHONY : libs-mdr/lib-timing.s

# target to generate assembly for a file
libs-mdr/lib-timing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mdr.dir/build.make CMakeFiles/mdr.dir/libs-mdr/lib-timing.c.s
.PHONY : libs-mdr/lib-timing.c.s

src/lib-anon-proxy.o: src/lib-anon-proxy.c.o
.PHONY : src/lib-anon-proxy.o

# target to build an object file
src/lib-anon-proxy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anon-proxy.dir/build.make CMakeFiles/anon-proxy.dir/src/lib-anon-proxy.c.o
.PHONY : src/lib-anon-proxy.c.o

src/lib-anon-proxy.i: src/lib-anon-proxy.c.i
.PHONY : src/lib-anon-proxy.i

# target to preprocess a source file
src/lib-anon-proxy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anon-proxy.dir/build.make CMakeFiles/anon-proxy.dir/src/lib-anon-proxy.c.i
.PHONY : src/lib-anon-proxy.c.i

src/lib-anon-proxy.s: src/lib-anon-proxy.c.s
.PHONY : src/lib-anon-proxy.s

# target to generate assembly for a file
src/lib-anon-proxy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anon-proxy.dir/build.make CMakeFiles/anon-proxy.dir/src/lib-anon-proxy.c.s
.PHONY : src/lib-anon-proxy.c.s

src/lib-elgamal-mod.o: src/lib-elgamal-mod.c.o
.PHONY : src/lib-elgamal-mod.o

# target to build an object file
src/lib-elgamal-mod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elgamal-mod.dir/build.make CMakeFiles/elgamal-mod.dir/src/lib-elgamal-mod.c.o
.PHONY : src/lib-elgamal-mod.c.o

src/lib-elgamal-mod.i: src/lib-elgamal-mod.c.i
.PHONY : src/lib-elgamal-mod.i

# target to preprocess a source file
src/lib-elgamal-mod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elgamal-mod.dir/build.make CMakeFiles/elgamal-mod.dir/src/lib-elgamal-mod.c.i
.PHONY : src/lib-elgamal-mod.c.i

src/lib-elgamal-mod.s: src/lib-elgamal-mod.c.s
.PHONY : src/lib-elgamal-mod.s

# target to generate assembly for a file
src/lib-elgamal-mod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/elgamal-mod.dir/build.make CMakeFiles/elgamal-mod.dir/src/lib-elgamal-mod.c.s
.PHONY : src/lib-elgamal-mod.c.s

test/test-anon-proxy.o: test/test-anon-proxy.c.o
.PHONY : test/test-anon-proxy.o

# target to build an object file
test/test-anon-proxy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-anon-proxy.dir/build.make CMakeFiles/test-anon-proxy.dir/test/test-anon-proxy.c.o
.PHONY : test/test-anon-proxy.c.o

test/test-anon-proxy.i: test/test-anon-proxy.c.i
.PHONY : test/test-anon-proxy.i

# target to preprocess a source file
test/test-anon-proxy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-anon-proxy.dir/build.make CMakeFiles/test-anon-proxy.dir/test/test-anon-proxy.c.i
.PHONY : test/test-anon-proxy.c.i

test/test-anon-proxy.s: test/test-anon-proxy.c.s
.PHONY : test/test-anon-proxy.s

# target to generate assembly for a file
test/test-anon-proxy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-anon-proxy.dir/build.make CMakeFiles/test-anon-proxy.dir/test/test-anon-proxy.c.s
.PHONY : test/test-anon-proxy.c.s

test/test-elgamal-mod.o: test/test-elgamal-mod.c.o
.PHONY : test/test-elgamal-mod.o

# target to build an object file
test/test-elgamal-mod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-elgamal-mod.dir/build.make CMakeFiles/test-elgamal-mod.dir/test/test-elgamal-mod.c.o
.PHONY : test/test-elgamal-mod.c.o

test/test-elgamal-mod.i: test/test-elgamal-mod.c.i
.PHONY : test/test-elgamal-mod.i

# target to preprocess a source file
test/test-elgamal-mod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-elgamal-mod.dir/build.make CMakeFiles/test-elgamal-mod.dir/test/test-elgamal-mod.c.i
.PHONY : test/test-elgamal-mod.c.i

test/test-elgamal-mod.s: test/test-elgamal-mod.c.s
.PHONY : test/test-elgamal-mod.s

# target to generate assembly for a file
test/test-elgamal-mod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-elgamal-mod.dir/build.make CMakeFiles/test-elgamal-mod.dir/test/test-elgamal-mod.c.s
.PHONY : test/test-elgamal-mod.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... anon-proxy"
	@echo "... elgamal-mod"
	@echo "... main-anon-proxy"
	@echo "... main-elgamal-mod"
	@echo "... mdr"
	@echo "... test-anon-proxy"
	@echo "... test-elgamal-mod"
	@echo "... examples/main-anon-proxy.o"
	@echo "... examples/main-anon-proxy.i"
	@echo "... examples/main-anon-proxy.s"
	@echo "... examples/main-elgamal-mod.o"
	@echo "... examples/main-elgamal-mod.i"
	@echo "... examples/main-elgamal-mod.s"
	@echo "... libs-mdr/lib-mesg.o"
	@echo "... libs-mdr/lib-mesg.i"
	@echo "... libs-mdr/lib-mesg.s"
	@echo "... libs-mdr/lib-misc.o"
	@echo "... libs-mdr/lib-misc.i"
	@echo "... libs-mdr/lib-misc.s"
	@echo "... libs-mdr/lib-powm.o"
	@echo "... libs-mdr/lib-powm.i"
	@echo "... libs-mdr/lib-powm.s"
	@echo "... libs-mdr/lib-timing.o"
	@echo "... libs-mdr/lib-timing.i"
	@echo "... libs-mdr/lib-timing.s"
	@echo "... src/lib-anon-proxy.o"
	@echo "... src/lib-anon-proxy.i"
	@echo "... src/lib-anon-proxy.s"
	@echo "... src/lib-elgamal-mod.o"
	@echo "... src/lib-elgamal-mod.i"
	@echo "... src/lib-elgamal-mod.s"
	@echo "... test/test-anon-proxy.o"
	@echo "... test/test-anon-proxy.i"
	@echo "... test/test-anon-proxy.s"
	@echo "... test/test-elgamal-mod.o"
	@echo "... test/test-elgamal-mod.i"
	@echo "... test/test-elgamal-mod.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

