# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/cryptoeng/SLWL11

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/cryptoeng/SLWL11

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/cryptoeng/SLWL11/CMakeFiles /home/ubuntu/cryptoeng/SLWL11//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/cryptoeng/SLWL11/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libs

# Build rule for target.
libs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libs
.PHONY : libs

# fast build rule for target.
libs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/build
.PHONY : libs/fast

#=============================================================================
# Target rules for targets named main-elgamal-mod

# Build rule for target.
main-elgamal-mod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main-elgamal-mod
.PHONY : main-elgamal-mod

# fast build rule for target.
main-elgamal-mod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-elgamal-mod.dir/build.make CMakeFiles/main-elgamal-mod.dir/build
.PHONY : main-elgamal-mod/fast

#=============================================================================
# Target rules for targets named bench-elgamal-mod

# Build rule for target.
bench-elgamal-mod: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench-elgamal-mod
.PHONY : bench-elgamal-mod

# fast build rule for target.
bench-elgamal-mod/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench-elgamal-mod.dir/build.make CMakeFiles/bench-elgamal-mod.dir/build
.PHONY : bench-elgamal-mod/fast

#=============================================================================
# Target rules for targets named anon-proxy

# Build rule for target.
anon-proxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 anon-proxy
.PHONY : anon-proxy

# fast build rule for target.
anon-proxy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anon-proxy.dir/build.make CMakeFiles/anon-proxy.dir/build
.PHONY : anon-proxy/fast

libs/lib-mesg.o: libs/lib-mesg.c.o
.PHONY : libs/lib-mesg.o

# target to build an object file
libs/lib-mesg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-mesg.c.o
.PHONY : libs/lib-mesg.c.o

libs/lib-mesg.i: libs/lib-mesg.c.i
.PHONY : libs/lib-mesg.i

# target to preprocess a source file
libs/lib-mesg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-mesg.c.i
.PHONY : libs/lib-mesg.c.i

libs/lib-mesg.s: libs/lib-mesg.c.s
.PHONY : libs/lib-mesg.s

# target to generate assembly for a file
libs/lib-mesg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-mesg.c.s
.PHONY : libs/lib-mesg.c.s

libs/lib-misc.o: libs/lib-misc.c.o
.PHONY : libs/lib-misc.o

# target to build an object file
libs/lib-misc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-misc.c.o
.PHONY : libs/lib-misc.c.o

libs/lib-misc.i: libs/lib-misc.c.i
.PHONY : libs/lib-misc.i

# target to preprocess a source file
libs/lib-misc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-misc.c.i
.PHONY : libs/lib-misc.c.i

libs/lib-misc.s: libs/lib-misc.c.s
.PHONY : libs/lib-misc.s

# target to generate assembly for a file
libs/lib-misc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-misc.c.s
.PHONY : libs/lib-misc.c.s

libs/lib-timing.o: libs/lib-timing.c.o
.PHONY : libs/lib-timing.o

# target to build an object file
libs/lib-timing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-timing.c.o
.PHONY : libs/lib-timing.c.o

libs/lib-timing.i: libs/lib-timing.c.i
.PHONY : libs/lib-timing.i

# target to preprocess a source file
libs/lib-timing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-timing.c.i
.PHONY : libs/lib-timing.c.i

libs/lib-timing.s: libs/lib-timing.c.s
.PHONY : libs/lib-timing.s

# target to generate assembly for a file
libs/lib-timing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/libs/lib-timing.c.s
.PHONY : libs/lib-timing.c.s

src/anon-proxy.o: src/anon-proxy.c.o
.PHONY : src/anon-proxy.o

# target to build an object file
src/anon-proxy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anon-proxy.dir/build.make CMakeFiles/anon-proxy.dir/src/anon-proxy.c.o
.PHONY : src/anon-proxy.c.o

src/anon-proxy.i: src/anon-proxy.c.i
.PHONY : src/anon-proxy.i

# target to preprocess a source file
src/anon-proxy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anon-proxy.dir/build.make CMakeFiles/anon-proxy.dir/src/anon-proxy.c.i
.PHONY : src/anon-proxy.c.i

src/anon-proxy.s: src/anon-proxy.c.s
.PHONY : src/anon-proxy.s

# target to generate assembly for a file
src/anon-proxy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/anon-proxy.dir/build.make CMakeFiles/anon-proxy.dir/src/anon-proxy.c.s
.PHONY : src/anon-proxy.c.s

src/bench-elgamal-mod.o: src/bench-elgamal-mod.c.o
.PHONY : src/bench-elgamal-mod.o

# target to build an object file
src/bench-elgamal-mod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench-elgamal-mod.dir/build.make CMakeFiles/bench-elgamal-mod.dir/src/bench-elgamal-mod.c.o
.PHONY : src/bench-elgamal-mod.c.o

src/bench-elgamal-mod.i: src/bench-elgamal-mod.c.i
.PHONY : src/bench-elgamal-mod.i

# target to preprocess a source file
src/bench-elgamal-mod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench-elgamal-mod.dir/build.make CMakeFiles/bench-elgamal-mod.dir/src/bench-elgamal-mod.c.i
.PHONY : src/bench-elgamal-mod.c.i

src/bench-elgamal-mod.s: src/bench-elgamal-mod.c.s
.PHONY : src/bench-elgamal-mod.s

# target to generate assembly for a file
src/bench-elgamal-mod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench-elgamal-mod.dir/build.make CMakeFiles/bench-elgamal-mod.dir/src/bench-elgamal-mod.c.s
.PHONY : src/bench-elgamal-mod.c.s

src/elgamal-mod.o: src/elgamal-mod.c.o
.PHONY : src/elgamal-mod.o

# target to build an object file
src/elgamal-mod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/elgamal-mod.c.o
.PHONY : src/elgamal-mod.c.o

src/elgamal-mod.i: src/elgamal-mod.c.i
.PHONY : src/elgamal-mod.i

# target to preprocess a source file
src/elgamal-mod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/elgamal-mod.c.i
.PHONY : src/elgamal-mod.c.i

src/elgamal-mod.s: src/elgamal-mod.c.s
.PHONY : src/elgamal-mod.s

# target to generate assembly for a file
src/elgamal-mod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libs.dir/build.make CMakeFiles/libs.dir/src/elgamal-mod.c.s
.PHONY : src/elgamal-mod.c.s

src/main-elgamal-mod.o: src/main-elgamal-mod.c.o
.PHONY : src/main-elgamal-mod.o

# target to build an object file
src/main-elgamal-mod.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-elgamal-mod.dir/build.make CMakeFiles/main-elgamal-mod.dir/src/main-elgamal-mod.c.o
.PHONY : src/main-elgamal-mod.c.o

src/main-elgamal-mod.i: src/main-elgamal-mod.c.i
.PHONY : src/main-elgamal-mod.i

# target to preprocess a source file
src/main-elgamal-mod.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-elgamal-mod.dir/build.make CMakeFiles/main-elgamal-mod.dir/src/main-elgamal-mod.c.i
.PHONY : src/main-elgamal-mod.c.i

src/main-elgamal-mod.s: src/main-elgamal-mod.c.s
.PHONY : src/main-elgamal-mod.s

# target to generate assembly for a file
src/main-elgamal-mod.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main-elgamal-mod.dir/build.make CMakeFiles/main-elgamal-mod.dir/src/main-elgamal-mod.c.s
.PHONY : src/main-elgamal-mod.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... anon-proxy"
	@echo "... bench-elgamal-mod"
	@echo "... libs"
	@echo "... main-elgamal-mod"
	@echo "... libs/lib-mesg.o"
	@echo "... libs/lib-mesg.i"
	@echo "... libs/lib-mesg.s"
	@echo "... libs/lib-misc.o"
	@echo "... libs/lib-misc.i"
	@echo "... libs/lib-misc.s"
	@echo "... libs/lib-timing.o"
	@echo "... libs/lib-timing.i"
	@echo "... libs/lib-timing.s"
	@echo "... src/anon-proxy.o"
	@echo "... src/anon-proxy.i"
	@echo "... src/anon-proxy.s"
	@echo "... src/bench-elgamal-mod.o"
	@echo "... src/bench-elgamal-mod.i"
	@echo "... src/bench-elgamal-mod.s"
	@echo "... src/elgamal-mod.o"
	@echo "... src/elgamal-mod.i"
	@echo "... src/elgamal-mod.s"
	@echo "... src/main-elgamal-mod.o"
	@echo "... src/main-elgamal-mod.i"
	@echo "... src/main-elgamal-mod.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

